name: Build and deploy to GitHub Pages (Actions artifact)

on:
  push:
    branches: [ main ]

# permissions necessari per upload + deploy
permissions:
  contents: read
  pages: write
  id-token: write

# evita deploy concorrenti
concurrency:
  group: pages-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare dist (copy CNAME + 404)
        run: |
          cp CNAME dist/ 2>/dev/null || true
          if [ -f dist/index.html ]; then cp dist/index.html dist/404.html; fi

      - name: Upload artifact for GitHub Pages
        # usa versione aggiornata per evitare dipendenze a upload-artifact@v3
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
